<?php

namespace AppBundle\Repository;

/**
 * SressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SressRepository extends \Doctrine\ORM\EntityRepository
{
}
